CREATE DATABASE SalaReuniao;

CREATE TABLE SALA_DE_REUNIAO(
    Hora DATETIME NOT NULL,
    Sala1 BIT NOT NULL,
    Sala2 VARCHAR NULL,
    Sala3 BIT NULL,
    Funcionario NVARCHAR (5) NULL,
    Cargo NVARCHAR (30) NOT NULL,
    Telefone NVARCHAR (20) NOT NULL,
    NumeroDeLugares INT NOT NULL 
);

EXEC sp_rename 'SALA_DE_REUNIAO.Hora', 'Horarios', 'COLUMN';
EXEC sp_rename 'SALA_DE_REUNIAO.Telefone', 'Ramal', 'COLUMN';

ALTER TABLE SALA_DE_REUNIAO ALTER COLUMN Sala2 BIT NOT NULL;
ALTER TABLE SALA_DE_REUNIAO ALTER COLUMN Sala3 BIT NOT NULL;
ALTER TABLE SALA_DE_REUNIAO ALTER COLUMN Funcionario NVARCHAR(100) NOT NULL;
ALTER TABLE SALA_DE_REUNIAO ALTER COLUMN Ramal INT NOT NULL;