USE ESTACIONAMENTO;
SELECT AVG(CAPACIDADE) AS MEDIACAPACIDADE FROM PATIO;

USE ESTACIONAMENTO;
SELECT COUNT(ID) AS QUANTIDADE FROM ESTACIONAMENTO 
WHERE DATASAIDA IS NULL;

USE ESTACIONAMENTO;
SELECT MAX(ANO) AS ANO FROM VEICULO;

USE ESTACIONAMENTO;
SELECT MIN(ANO) AS ANO FROM VEICULO;


USE ESTACIONAMENTO;
SELECT DAY(DATAENTRADA) AS DIA FROM ESTACIONAMENTO;

USE ESTACIONAMENTO;
SELECT SUBSTRING(PLACA, 5, 8) AS DIA FROM VEICULO;

USE ESTACIONAMENTO;
UPDATE VEICULO SET COR = LOWER(COR);

USE ESTACIONAMENTO;
SELECT CONCAT(c.NOME, ' | ', v.PLACA, ' | ', m.DESCRICAO, ' | ', e.DATAENTRADA, ' | ', p.ENDERECO) AS INFORMACAO
    FROM CLIENTE c 
    INNER JOIN VEICULO v ON v.CPFCLIENTE = c.CPF
    INNER JOIN MODELO m ON m.ID = v.MODELOID
    INNER JOIN ESTACIONAMENTO e ON e.PLACAVEICULO = v.PLACA
    INNER JOIN PATIO p ON p.ID = e.PATIOID