CREATE DATABASE ESTACIONAMENTO;

USE ESTACIONAMENTO
CREATE TABLE MODELO(
ID BIGINT IDENTITY(1,1) NOT NULL,
DESCRICAO VARCHAR(50) NOT NULL
CONSTRAINT PK_MODELO PRIMARY KEY (ID)
);

USE ESTACIONAMENTO
CREATE TABLE CLIENTE(
CPF BIGINT NOT NULL,
NOME VARCHAR(100) NOT NULL,
DATANASCIMENTO DATE NOT NULL
CONSTRAINT PK_CLIENTE PRIMARY KEY (CPF)
); 

USE ESTACIONAMENTO
CREATE TABLE PATIO(
ID BIGINT IDENTITY NOT NULL,
ENDERECO VARCHAR(200),
CAPACIDADE INT NOT NULL
CONSTRAINT PK_PATIO PRIMARY KEY (ID)
);

USE ESTACIONAMENTO
CREATE TABLE VEICULO(
PLACA VARCHAR(10) NOT NULL,
COR VARCHAR(50) NOT NULL,
ANO INT,
MODELOID BIGINT NOT NULL,
CPFCLIENTE BIGINT NOT NULL,
CONSTRAINT PK_VEICULO PRIMARY KEY (PLACA),
CONSTRAINT FK_MODELO FOREIGN KEY (MODELOID) REFERENCES MODELO (ID),
CONSTRAINT FK_CLIENTE FOREIGN KEY (CPFCLIENTE) REFERENCES CLIENTE (CPF)
);

USE ESTACIONAMENTO
CREATE TABLE ESTACIONAMENTO(
ID BIGINT IDENTITY(1,1) NOT NULL,
DATAENTRADA DATETIME NOT NULL,
DATASAIDA DATETIME,
PATIOID BIGINT NOT NULL,
PLACAVEICULO VARCHAR(10) NOT NULL
CONSTRAINT PK_ESTACIONAMENTO PRIMARY KEY (ID),
CONSTRAINT FK_PATIO FOREIGN KEY (PATIOID) REFERENCES PATIO (ID),
CONSTRAINT FK_VEICULO FOREIGN KEY (PLACAVEICULO) REFERENCES VEICULO (PLACA)
);

-- POPULA MODELO
USE ESTACIONAMENTO
INSERT MODELO (DESCRICAO) VALUES ('PALIO')
INSERT MODELO (DESCRICAO) VALUES ('UNO')
INSERT MODELO (DESCRICAO) VALUES ('CELTA')

-- POPULA CLIENTE
USE ESTACIONAMENTO
INSERT CLIENTE(CPF, NOME, DATANASCIMENTO) VALUES (59837066083, 'Mariane', '1994-05-24')
INSERT CLIENTE (CPF, NOME, DATANASCIMENTO) VALUES (74828209069, 'Mateus', '2002-01-23')
INSERT CLIENTE (CPF, NOME, DATANASCIMENTO) VALUES (26524091078, 'Eduardo', '1988-08-15')

--POPULA PATIO
USE ESTACIONAMENTO
INSERT PATIO(CAPACIDADE) VALUES (40)
INSERT PATIO(CAPACIDADE) VALUES (50)
INSERT PATIO(CAPACIDADE) VALUES (15)

--POPULA VEICULO
USE ESTACIONAMENTO
INSERT VEICULO(PLACA, COR, MODELOID, CPFCLIENTE, ANO) VALUES ('JJJ-2020', 'VERDE', 1, 59837066083, 2020)
INSERT VEICULO(PLACA, COR, MODELOID, CPFCLIENTE, ANO) VALUES ('JEG-1010', 'BORDO', 2, 74828209069, 2016)
INSERT VEICULO(PLACA, COR, MODELOID, CPFCLIENTE, ANO) VALUES ('MEC-1018', 'BRANCO', 3, 26524091078, 2018)

--POPULA ESTACIONAMENTO
USE ESTACIONAMENTO
INSERT ESTACIONAMENTO(DATAENTRADA, PATIOID, PLACAVEICULO) VALUES (GETDATE(), 1, 'MEC-1018')
INSERT ESTACIONAMENTO(DATAENTRADA, PATIOID, PLACAVEICULO) VALUES (GETDATE(), 1, 'JJJ-2020')
INSERT ESTACIONAMENTO(DATAENTRADA, PATIOID, PLACAVEICULO) VALUES (GETDATE(), 2, 'JEG-1010')

USE ESTACIONAMENTO
SELECT V.PLACA, C.NOME
FROM VEICULO V
INNER JOIN CLIENTE C ON (V.CPFCLIENTE = C.CPF)

USE ESTACIONAMENTO
SELECT C.CPF, C.NOME
FROM VEICULO V
INNER JOIN CLIENTE C ON (V.CPFCLIENTE = C.CPF)
WHERE V.PLACA = 'JJJ-2020'


USE ESTACIONAMENTO
SELECT V.PLACA, V.COR
FROM VEICULO V
INNER JOIN CLIENTE C ON (V.CPFCLIENTE = C.CPF)
INNER JOIN ESTACIONAMENTO E ON (E.PLACAVEICULO = V.PLACA)
WHERE E.ID = 1
 

USE ESTACIONAMENTO
SELECT V.PLACA, V.ANO
FROM VEICULO V
INNER JOIN CLIENTE C ON (V.CPFCLIENTE = C.CPF)
INNER JOIN ESTACIONAMENTO E ON (E.PLACAVEICULO = V.PLACA)
WHERE E.ID = 1

USE ESTACIONAMENTO
SELECT V.ANO, M.DESCRICAO
FROM VEICULO V
INNER JOIN MODELO M ON (V.MODELOID = M.ID)
WHERE V.ANO > 2000;
 
USE ESTACIONAMENTO
SELECT P.ENDERECO, E.DATAENTRADA, E.DATASAIDA
FROM VEICULO V
INNER JOIN CLIENTE C ON (V.CPFCLIENTE = C.CPF)
INNER JOIN ESTACIONAMENTO E ON (E.PLACAVEICULO = V.PLACA)
INNER JOIN PATIO P ON (E.PATIOID = P.ID)
WHERE V.PLACA = 'JEG-1010'


USE ESTACIONAMENTO
SELECT COUNT(E.ID)
FROM VEICULO V
INNER JOIN ESTACIONAMENTO E ON (V.PLACA = E.PLACAVEICULO)
WHERE V.COR = 'VERDE'


USE ESTACIONAMENTO
SELECT C.* 
FROM CLIENTE C
INNER JOIN VEICULO V ON (C.CPF = V.CPFCLIENTE)
INNER JOIN MODELO M ON (V.MODELOID = M.ID)
WHERE M.ID = 1
 
 
 USE ESTACIONAMENTO
 SELECT V.PLACA, E.DATAENTRADA, E.DATASAIDA
 FROM VEICULO V 
 INNER JOIN ESTACIONAMENTO E ON (V.PLACA = E.PLACAVEICULO)
 WHERE V.COR = 'VERDE'
 
USE ESTACIONAMENTO
SELECT E.*
FROM VEICULO V
INNER JOIN ESTACIONAMENTO E ON (V.PLACA = E.PLACAVEICULO)
WHERE V.PLACA = 'JJJ-2020'

USE ESTACIONAMENTO
SELECT C.NOME
FROM VEICULO V
INNER JOIN CLIENTE C ON (V.CPFCLIENTE = C.CPF)
INNER JOIN ESTACIONAMENTO E ON (E.PLACAVEICULO = V.PLACA)
WHERE E.ID = 2

USE ESTACIONAMENTO
SELECT C.CPF
FROM VEICULO V
INNER JOIN CLIENTE C ON (V.CPFCLIENTE = C.CPF)
INNER JOIN ESTACIONAMENTO E ON (E.PLACAVEICULO = V.PLACA)
WHERE E.ID = 3


USE ESTACIONAMENTO
SELECT M.DESCRICAO
FROM VEICULO V
INNER JOIN MODELO M ON (V.MODELOID = M.ID)
INNER JOIN ESTACIONAMENTO E ON (E.PLACAVEICULO = V.PLACA)
WHERE E.ID = 3


USE ESTACIONAMENTO
SELECT V.PLACA, C.NOME, M.DESCRICAO
FROM VEICULO V
INNER JOIN MODELO M ON (V.MODELOID = M.ID)
INNER JOIN CLIENTE C ON (V.CPFCLIENTE = C.CPF)

