
SELECT ANO FROM VEICULO where ANO = 2016


CREATE NONCLUSTERED INDEX IX_ANO ON VEICULO (ANO);


SELECT ANO FROM VEICULO where ANO = 2016;

 
CREATE UNIQUE INDEX IXU_PLACAVEICULO ON ESTACIONAMENTO (PLACAVEICULO);
INSERT INTO ESTACIONAMENTO (DATAENTRADA, PATIOID, PLACAVEICULO) VALUES (GETDATE(), 1, 'MEC-1018')


CREATE NONCLUSTERED INDEX IX_PLACAVEICULO_ID ON ESTACIONAMENTO (PLACAVEICULO) INCLUDE(ID, DATAENTRADA);


CREATE NONCLUSTERED INDEX IX_DATAENTRADA ON ESTACIONAMENTO (DATAENTRADA) INCLUDE (ID, PLACAVEICULO, DATASAIDA);


DROP INDEX IXU_PLACAVEICULO ON ESTACIONAMENTO;


INSERT INTO ESTACIONAMENTO (DATAENTRADA, PATIOID, PLACAVEICULO) VALUES (GETDATE(), 1, 'MEC-1018')
INSERT INTO ESTACIONAMENTO (DATAENTRADA, PATIOID, PLACAVEICULO) VALUES (GETDATE(), 1, 'MEC-1018')
INSERT INTO ESTACIONAMENTO (DATAENTRADA, PATIOID, PLACAVEICULO) VALUES (GETDATE(), 1, 'MEC-1018')
INSERT INTO ESTACIONAMENTO (DATAENTRADA, PATIOID, PLACAVEICULO) VALUES (GETDATE(), 1, 'MEC-1018')
INSERT INTO ESTACIONAMENTO (DATAENTRADA, PATIOID, PLACAVEICULO) VALUES (GETDATE(), 1, 'MEC-1018')
INSERT INTO ESTACIONAMENTO (DATAENTRADA, PATIOID, PLACAVEICULO) VALUES (GETDATE(), 1, 'MEC-1018')
INSERT INTO ESTACIONAMENTO (DATAENTRADA, PATIOID, PLACAVEICULO) VALUES (GETDATE(), 1, 'MEC-1018')
INSERT INTO ESTACIONAMENTO (DATAENTRADA, PATIOID, PLACAVEICULO) VALUES (GETDATE(), 1, 'MEC-1018')
INSERT INTO ESTACIONAMENTO (DATAENTRADA, PATIOID, PLACAVEICULO) VALUES (GETDATE(), 1, 'MEC-1018')
INSERT INTO ESTACIONAMENTO (DATAENTRADA, PATIOID, PLACAVEICULO) VALUES (GETDATE(), 1, 'MEC-1018')
INSERT INTO ESTACIONAMENTO (DATAENTRADA, PATIOID, PLACAVEICULO) VALUES (GETDATE(), 1, 'MEC-1018')

ALTER INDEX IX_DATAENTRADA ON ESTACIONAMENTO REBUILD;
ALTER INDEX IX_PLACAVEICULO_ID ON ESTACIONAMENTO REBUILD;
ALTER INDEX PK_ESTACIONAMENTO ON ESTACIONAMENTO REBUILD;